### ISSUE TITLE
ensureConcluded fails when channel has been progressed to final

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#147]
**Location:** backend/eth/conclude, contracts/Adjudicator.sol

**Problem:** When a channel has been force-update on-chain into a final state, the participants will not have fully signed states. Now, when calling `ensureConcluded`, it will call `concludeFinal`, which expects a fully-signed state and thus fails.

**Idea:** If a channel has been force-updated into final, the client should call `conclude` instead of `concludeFinal`, because `conclude` does not require signatures. The client must be able to detect whether a channel is in a final state on-chain. Usually, we indicate that by setting `phase = CONCLUDED`. Hence, I suggest that we change the contract such that if a state is force-updated to final, we automatically set `phase = CONCLUDED`.

Update: We can also apply a quick fix that doesn't require a change in the contracts. We can check whether the current on-chain phase is `FORCE_EXECUTION`. If this is the case, we know that the state resulted from force execution, which means we do not have the all signatures and need to call `conclude` instead of `concludeFinal`.

**Comment by ggwpez** [comment]
How did you detect this? Do you plan on adding a test for this case?  
@matthiasgeihs

**Comment by matthiasgeihs** [comment]
While working on the app-channel example.

It would probably make sense to add a test case, yes.

**Comment by manoranjith** [comment]
@matthiasgeihs On a related note, did you try concluding an app channel which 
1. is not finalized.
2. has no on-chain progressions.

From my understanding, this would always fail. Because, timeout will be reset in [`line 402 of Adjudicator.sol`](https://github.com/hyperledger-labs/perun-eth-contracts/blob/73b45dee752da4af2f95044c64c8b214459cda32/contracts/Adjudicator.sol#L401), condition in line 405 will not be met, causing the call to fail.
