### ISSUE TITLE
`Accounts` in simple.Wallet should be unexported and protected against concurrent access

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#16]
The simple.Wallet implementation holds a struct `Accounts`. This is currently exported and not protected against concurrent access.

We should unexport it (i.e., `Accounts` -> `accounts`) and protect it with a read-write mutex.

**Comment by matthiasgeihs** [comment]
We should also consider renaming `NewTransactor` to `NewTransactorFactory`.

**Comment by cryptphil** [comment]
> We should also consider renaming `NewTransactor` to `NewTransactorFactory`.

Do you mean the method in the actual interface or in simple wallet?
If we only rename `NewTransactor` to `NewTransactorFactory` in simple wallet, then it wouldn't implement the Transactor interface anymore.

**Comment by ggwpez** [comment]
I dont quite understand why we named the transactor of the simple wallet `TransactorFactory` instead of `Transactor` like in the other wallet implementations.  
It still is a `Transactor` since it implements the `Transactor` interface.  
  
Anyway, we should extend the test to detect faulty wallet implementations.
