### ISSUE TITLE
🐛 `SubChannelProposal` does not allow to specify different account

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#241]
### Location
client/proposalmsgs.go, client/proposal.go: type `SubChannelProposal`

### Problem
Type `SubChannelProposal` does not allow to specify a different account than the one used in the parent channel. However, there may be applications where the sub-channels funds should be controllable with a separate account.

### Proposal
Include an account address in `SubChannelProposal` and `SubChannelProposalAcc` and derive the channel accounts from that.

**Comment by sebastianst** [comment]
AFAIR this was a conscious decision because when we designed sub-channels, the purpose of them was to be a sub-channel in a tree of channels with only one root channel at the top, so all sub-channels would implicitly have the same participants. Also, the smart contract logic did/does(?) assume that all sub-channels have the same participants as the root channel. A participant address was/is(?) taken from the root channel parameter's participants array by index.
