### ISSUE TITLE
ERC20 Depositor nonce race

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#62]
**Problem**: The `ERC20Depositor` sends two transactions (increase allowance and deposit) in the same block.  
This seems to be causing issues with how the nonce is determined. Sometimes its transactions revert.

**Possible solutions**:  
1. Manually increasing the nonce by one after the first TX
2. Wait for the first TX to be mined (which is actually the job of the `Funder`)
3. Poll the nonce multiple times until a new one is returned

I opt for `1.` as it seems the easiest and fastest.

**Comment by manoranjith** [comment]
I think `2` could be a better option, because the `deposit` transaction is sent only after the previous transaction is confirmed. Which should be the case logically ?
Thoughts on this @ggwpez ?

**Comment by ggwpez** [comment]
> I think `2` could be a better option, because the `deposit` transaction is sent only after the previous transaction is confirmed. Which should be the case logically ?
> Thoughts on this @ggwpez ?

It is probably the very stable, but also much slower than `1.` since it will never try to send both TX in the same block.  
If we use `1.` we can keep our current design and be faster than `2.`.  

We currently have the abstraction of the `Depositor` that it itself does not to confirm the Transactions since the `Funder` can better do it:  
```go
Depositor interface {
	Deposit(context.Context, DepositReq) (types.Transactions, error)
	NumTX() uint32
}
```
so its a bit sad if we then add Transaction confirmation in the `Depositor`, which is currently only sending the TX and then the `Funder` confirms them.  
Any ideas @matthiasgeihs ?

**Comment by manoranjith** [comment]
I agree that `1` could be faster. But the problem I see is,

say, the user of go-perun opens two channels in quick succession (as per current design, this happens concurrently), the
- fund call for channel 1 will get correct nonces for both transactions.
- fund call for channel 2 is likely two get an incorrect nonce for it's first transaction. Because the increment in nonce for second transaction of channel 1 was made locally. The blockchain node we are interacting with is not aware of this.

Considering the above scenario, I think `3` will be a both `stable` (we use the latest nonce as known by the blockchain node) and `fast` option (the possibility that both transactions are included in the same block remains open). 
@ggwpez

**Comment by manoranjith** [comment]
@ggwpez I have tried out methods 1 and 3. I will submit PRs for both the approaches in go-perun repo for review.

However, since the go-perun does not have the setup for running tests using `ganache-cli`, I have created demo pull requests in perun-node repo, where these changes are tested using ganache-cli.
Links: [Failing tests](https://app.circleci.com/pipelines/github/hyperledger-labs/perun-node/673/workflows/83994e97-2299-4407-b8ad-e9924afa4995/jobs/1437/steps?invite=true#step-109-3048),  [approach 1](https://github.com/hyperledger-labs/perun-node/pull/214) and [approach 3](https://github.com/hyperledger-labs/perun-node/pulls214).
