### ISSUE TITLE
Easier method for creating and handling an allocation

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#63]
At the moment, creating a channel allocation for channel opening is not very convenient and can be confusing. Even for just a single asset channel it looks like the following.
```
channel.Allocation{
	Assets:   []channel.Asset{asset},
	Balances: [][]*big.Int{etherToWei(myBalEth, peerBalEth)},
}
```

We may want to change the Allocation struct and provide helper methods for that.

The allocation struct could hold a `map[Asset]AccountBalances`, where AccountBalances is a map from accounts to integers.

**Comment by ggwpez** [comment]
This is not only a problem when proposing a channel but also when receiving it.  
The receiver has to go through this rather ugly struct to find out whats going on.

Two remarks:  
1. If you just use a `map[Asset]AccountBalances` map then the order of the assets is not fixed anymore. This could cause issues on-chain. So we would maybe need to define an internal order where we order the assets alphabetically by their address.
2. You would need to write wrappers for the `Allocation` since otherwise the en/decoding for abigen would not work.
3. What do you think about `SubAlloc`? It suffers more or less from the same problem, but rewriting this would take a while :see_no_evil:

**Comment by matthiasgeihs** [comment]
1. The order would be determined by a list []Asset, attached to the Allocation:
```go
type Allocation struct {
    assets []Asset
    balances map[Asset]map[Account]*big.Int
}
```
2. Definitely.
3. Probably worth thinking about it.

**Comment by ggwpez** [comment]
That looks good. Just thought about if there is a better way than using the interfaces  `Asset` and `Account` as map keys.
