### ISSUE TITLE
Funder discards error information

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#65]
Location: funder.go, func Fund

When something goes wrong during funding, the funder prioritizes error messages depending on their type. If there is an error of type `AssetFundingError`, any other errors are discarded. This is not a good behavior. For example, I just had an error during an `IncreaseAllowance` in the ERC20Depositor. The error was that the nonce could not be determined. However, I did not receive any information about this error as it was discarded. I just get:
```
time="2021-05-05T10:13:44+02:00" level=error msg="Could not fund asset" asset=0xb5c37Ee9C816D2DB2f6A9A020ce6a80af3993AD3 error="sending transaction: "
```

We should always log all errors.

**Comment by ggwpez** [comment]
We thought long about how to best to this, but there was no really satisfactory solution that we could come up with.  
The idea here was to make it easier to recover from funding errors.  
In case of an `AssetFundingError`, the user wants to withdraw his funds and not retry it. If it was just a connection error, he may want to retry it.  
This is why we prioritized this error over the other ones.  

I fully agree that we should always log them, but currently we have no logging policy on when and how to log.  
So it is not always clear which function should log an error, so that we also dont log them twice…  
Maybe we should address that first.

Manoranjiths change did not cause/change this.

**Comment by matthiasgeihs** [comment]
Thanks @ggwpez for the reply. I think one policy that we should be able to agree on is, never discard errors, always log them at least. More detailed logging policies to be discussed...
